<?php
return [
    [
        'transaction_number' => 1,
        'date' => '2025-04-14',
        'supplier_name' => 'مستلزمات محل',
        'product' => 'شرشوبه +بخور+بخاخه+معطر',
        'quantity' => '4',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 2,
        'date' => '2025-04-15',
        'supplier_name' => 'حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 18740.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 3,
        'date' => '2025-04-16',
        'supplier_name' => 'مستلزمات محل',
        'product' => 'اكياس',
        'quantity' => '1',
        'total' => 90.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 4,
        'date' => '2025-04-17',
        'supplier_name' => 'مستلزمات محل',
        'product' => 'شماعات',
        'quantity' => '1',
        'total' => 58.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 5,
        'date' => '2025-04-18',
        'supplier_name' => 'مصنع الرحاب',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 19025.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 6,
        'date' => '2025-04-19',
        'supplier_name' => 'مصنع وليد عبدالواحد',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 8500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 7,
        'date' => '2025-04-20',
        'supplier_name' => 'مستلزمات محل',
        'product' => 'اكياس تغليف+لزق',
        'quantity' => null,
        'total' => 215.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 8,
        'date' => '2025-04-21',
        'supplier_name' => 'حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 30300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 9,
        'date' => '2025-04-22',
        'supplier_name' => 'مستلزمات محل',
        'product' => 'كروت + علم',
        'quantity' => null,
        'total' => 1500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 10,
        'date' => '2025-04-29',
        'supplier_name' => 'حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 6384.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 11,
        'date' => '2025-04-29',
        'supplier_name' => 'مستلزمات محل',
        'product' => 'شماعات + اكياس',
        'quantity' => null,
        'total' => 314.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 12,
        'date' => '2025-04-30',
        'supplier_name' => 'المليونير',
        'product' => 'دفايات',
        'quantity' => null,
        'total' => 3320.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 13,
        'date' => '2025-10-04',
        'supplier_name' => 'حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 5079.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 14,
        'date' => '2025-10-12',
        'supplier_name' => 'ادهم مصنع شبرا',
        'product' => 'بضاعه دفايات رجالي',
        'quantity' => '100',
        'total' => 10600.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 15,
        'date' => '2025-10-15',
        'supplier_name' => 'مصنع الرحاب',
        'product' => 'بضاعة ترنجات',
        'quantity' => '24',
        'total' => 7190.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 16,
        'date' => '2025-10-20',
        'supplier_name' => 'بضاعة جسرالسويس',
        'product' => 'بضاعة ترنجات',
        'quantity' => '36',
        'total' => 6540.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 17,
        'date' => '2025-10-20',
        'supplier_name' => 'بضاعة المليونير',
        'product' => 'دفايات',
        'quantity' => '78',
        'total' => 5400.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 18,
        'date' => '2025-10-22',
        'supplier_name' => 'مصنع الرحاب',
        'product' => 'بضاعة ترنجات',
        'quantity' => '12',
        'total' => 3365.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 19,
        'date' => '2025-10-23',
        'supplier_name' => 'بضاعه لورد كيدز',
        'product' => 'ترنجات',
        'quantity' => '36',
        'total' => 13800.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 20,
        'date' => '2025-10-26',
        'supplier_name' => 'بضاعة نيو برازر',
        'product' => 'بضاعه',
        'quantity' => '48',
        'total' => 4900.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 21,
        'date' => '2025-10-26',
        'supplier_name' => 'بضاعة عبد الحي',
        'product' => 'بضاعه',
        'quantity' => '48',
        'total' => 14000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 22,
        'date' => '2025-10-26',
        'supplier_name' => 'بضاعة دلعين',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 17250.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 23,
        'date' => '2025-10-25',
        'supplier_name' => 'بضاعة بيجامتك',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 15000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 24,
        'date' => '2025-12-03',
        'supplier_name' => 'بضاعة دلعين',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 3750.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 25,
        'date' => '2025-12-08',
        'supplier_name' => 'حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 19214.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 26,
        'date' => '2025-12-16',
        'supplier_name' => 'بضاعة مصنع باريس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 9300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 27,
        'date' => '2025-12-30',
        'supplier_name' => 'بضاعة مصنع باريس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 9500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 28,
        'date' => '2025-12-30',
        'supplier_name' => 'بضاعه حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 4312.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 29,
        'date' => '2025-12-28',
        'supplier_name' => 'بضاعه حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 8100.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 30,
        'date' => '2025-12-28',
        'supplier_name' => 'بضاعه حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 1200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 31,
        'date' => '2025-12-28',
        'supplier_name' => 'بضاعه جينز',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 7000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 32,
        'date' => '2025-12-28',
        'supplier_name' => 'بضاعه حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 5000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 33,
        'date' => '2026-02-12',
        'supplier_name' => 'بضاعه النعيم',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 1500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 34,
        'date' => '2026-02-25',
        'supplier_name' => 'مكتب كساب فسكوز',
        'product' => 'بضاعه',
        'quantity' => null,
        'total' => 6400.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 35,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 36,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 37,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 38,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 39,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 40,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 41,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 42,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 43,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 44,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 45,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
    [
        'transaction_number' => 46,
        'date' => null,
        'supplier_name' => null,
        'product' => null,
        'quantity' => null,
        'total' => null,
        'notes' => null,
    ],
];
