<?php
return [
    [
        'transaction_number' => 1,
        'date' => '2025-04-15',
        'customer_name' => 'زمليه هبه',
        'product' => 'ترنج بيتي',
        'quantity' => '2',
        'unit_price' => '130+130',
        'total' => 260.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 2,
        'date' => '2025-04-18',
        'customer_name' => 'زمليه هبه',
        'product' => 'سلوبته بيني + سلوبته + شروال CK + تيشرت ناعم + (799) 10 + (3404) 8 + (3406) 8',
        'quantity' => '7',
        'unit_price' => '160+125+150+285+250+250+240+',
        'total' => 1550.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 3,
        'date' => '2025-04-19',
        'customer_name' => 'زمليه هبه',
        'product' => 'دفاية خاصة',
        'quantity' => '2',
        'unit_price' => '140+140',
        'total' => 280.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 4,
        'date' => '2025-04-25',
        'customer_name' => 'تقفيل حساب الاونلاين',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => 3000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 5,
        'date' => '2025-09-25',
        'customer_name' => 'جيهان',
        'product' => '2 تشيرت بسكوته + 2 شروال + ترنج محيرات',
        'quantity' => '5',
        'unit_price' => '340+340+360+360+300',
        'total' => 1700.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 6,
        'date' => '2025-10-01',
        'customer_name' => 'ايجار محل',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -1500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 7,
        'date' => '2025-10-01',
        'customer_name' => 'كهرباء',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 8,
        'date' => '2025-09-25',
        'customer_name' => 'حنان خالد',
        'product' => 'كاش',
        'quantity' => '1',
        'unit_price' => '70',
        'total' => 70.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 9,
        'date' => '2025-09-26',
        'customer_name' => 'احمد الفرماوي زميل هبه',
        'product' => '4  (3209) + (788) 4',
        'quantity' => '2',
        'unit_price' => '220+225',
        'total' => 445.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 10,
        'date' => '2025-09-26',
        'customer_name' => 'احمد الفرماوي زميل هبه',
        'product' => '(4304) 6 + (6007) 10 + (795) 10 + (788) 4',
        'quantity' => '4',
        'unit_price' => '250+345+250+225',
        'total' => 1070.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 11,
        'date' => '2025-09-26',
        'customer_name' => 'احمد الفرماوي زميل هبه',
        'product' => '(746) 14 + (739) 12 + (788) 8 + (3209) 4 + (3406) 8 + (788) 8',
        'quantity' => '6',
        'unit_price' => '315+320+225+220+240+225',
        'total' => 1545.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 12,
        'date' => '2025-09-27',
        'customer_name' => 'احمد زناتي',
        'product' => '(780) 14 + (780) 14 + (3209) 5',
        'quantity' => '3',
        'unit_price' => '315 + 315 + 220',
        'total' => 850.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 13,
        'date' => '2025-09-27',
        'customer_name' => 'احمد زناتي',
        'product' => 'شلبي 4 + قطه 4 +(4234) 4',
        'quantity' => '3',
        'unit_price' => '235 + 175 + 210',
        'total' => 620.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 14,
        'date' => '2025-09-29',
        'customer_name' => 'بضاعة حبيبه',
        'product' => 'ترنجات محيرات',
        'quantity' => '30',
        'unit_price' => null,
        'total' => -6114.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 15,
        'date' => '2025-09-29',
        'customer_name' => 'مستلزمات محل بلاستك',
        'product' => 'شماعات وشنط',
        'quantity' => null,
        'unit_price' => null,
        'total' => -314.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 16,
        'date' => '2025-09-30',
        'customer_name' => 'بضاعة المليونير',
        'product' => 'دفايات',
        'quantity' => '42',
        'unit_price' => null,
        'total' => -3320.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 17,
        'date' => '2025-09-30',
        'customer_name' => 'اسماء نسمه',
        'product' => '3 دفايات',
        'quantity' => '3',
        'unit_price' => '140+140+140',
        'total' => 420.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 18,
        'date' => '2025-09-30',
        'customer_name' => 'نسمه (سارة + هناء )',
        'product' => '2 دفايه',
        'quantity' => '2',
        'unit_price' => '140+140',
        'total' => 280.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 19,
        'date' => '2025-09-30',
        'customer_name' => 'عميل بنها',
        'product' => '2 ترنج + (3209)',
        'quantity' => '3',
        'unit_price' => '130+130+220',
        'total' => 440.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 20,
        'date' => '2025-10-01',
        'customer_name' => 'زميله نسمه',
        'product' => '(788) 4 + (3209) 4',
        'quantity' => '2',
        'unit_price' => '225+220',
        'total' => 445.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 21,
        'date' => '2025-10-01',
        'customer_name' => 'نسمه',
        'product' => '(820) 4 + دفايه جامبو + دفايه 12 + دفايه صبيان L+ 2 ترنج رجالي +',
        'quantity' => '4',
        'unit_price' => '245+140+125+120+240+250+315+225',
        'total' => 1830.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 22,
        'date' => '2025-10-01',
        'customer_name' => 'عميل محل',
        'product' => 'سلبته',
        'quantity' => '1',
        'unit_price' => '160',
        'total' => 160.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 23,
        'date' => '2025-10-01',
        'customer_name' => 'يافطه المحل',
        'product' => 'يافطه المحل',
        'quantity' => '1',
        'unit_price' => '355',
        'total' => -355.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 24,
        'date' => '2025-10-02',
        'customer_name' => 'سعاد نسمه',
        'product' => 'دفايه تايجر',
        'quantity' => '1',
        'unit_price' => '140',
        'total' => 140.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 25,
        'date' => '2025-10-02',
        'customer_name' => 'شيماء  نسمه',
        'product' => 'دفايه تايجر + دفايه جامبو',
        'quantity' => '2',
        'unit_price' => '140 + 140',
        'total' => 280.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 26,
        'date' => '2025-10-02',
        'customer_name' => 'زينب',
        'product' => '(3209) 3 + (739) 16 + (3404) 10 + (780) 16 + دفايه',
        'quantity' => '5',
        'unit_price' => '220+320+250+315+125',
        'total' => 1225.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 27,
        'date' => '2025-10-03',
        'customer_name' => 'حنفيه للمحل',
        'product' => 'حنفيه ونبلين',
        'quantity' => '1',
        'unit_price' => '125',
        'total' => -125.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 28,
        'date' => '2025-10-03',
        'customer_name' => 'مدير المدرسه هبه',
        'product' => '2 دفايه (200) + تيشرت بسكوته + تيشرت ناعم + 2 تيشرت + ترنج بناتي + ترنج (749)+ ck  + 2غطس',
        'quantity' => '12',
        'unit_price' => '140+140+170+150+200+200+130+160+285+270+270',
        'total' => 1800.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 29,
        'date' => '2025-10-03',
        'customer_name' => 'جيهان',
        'product' => '2 دفايه 12',
        'quantity' => '2',
        'unit_price' => '120+120',
        'total' => 240.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 30,
        'date' => '2025-10-03',
        'customer_name' => 'عبدالله هبه',
        'product' => '(3405) 12 + (3404) 6 + (3404) 12',
        'quantity' => '3',
        'unit_price' => '250 + 250 + 250',
        'total' => 750.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 31,
        'date' => '2025-10-03',
        'customer_name' => 'ايه زناتي',
        'product' => '(752) 18 + (780) 18 + دفايه جامبو',
        'quantity' => '3',
        'unit_price' => '325+315+140',
        'total' => 780.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 32,
        'date' => '2025-10-03',
        'customer_name' => 'ايمان عجلان',
        'product' => '(3404) 10 + (3404) 12',
        'quantity' => '3',
        'unit_price' => '250+320',
        'total' => 570.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 33,
        'date' => '2025-10-04',
        'customer_name' => 'حبيبه تكس',
        'product' => 'بضاعه',
        'quantity' => '4',
        'unit_price' => null,
        'total' => -5079.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 34,
        'date' => '2025-10-04',
        'customer_name' => 'عميل محل',
        'product' => 'دفايه 10 + دفايه 8 + (749) 2',
        'quantity' => '3',
        'unit_price' => '100+110+160',
        'total' => 370.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 35,
        'date' => '2025-10-04',
        'customer_name' => 'عميل محل',
        'product' => '2 دفايه 10 +(789) 8 + ترنج قطه 10',
        'quantity' => '3',
        'unit_price' => '120+120+220+210',
        'total' => 700.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 36,
        'date' => '2025-10-05',
        'customer_name' => 'ولاء نسمه',
        'product' => '2 دفايات صبياني 12 + دفايه تيجر + دفايه عرايس',
        'quantity' => '4',
        'unit_price' => '260+140+125',
        'total' => 520.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 37,
        'date' => '2025-10-05',
        'customer_name' => 'اخت ولاء نسمه',
        'product' => '2 دفايه صبياني + 2 دفايه عرايس + دفايه تايجر',
        'quantity' => '4',
        'unit_price' => '260+250',
        'total' => 500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 38,
        'date' => '2025-10-05',
        'customer_name' => 'مي نسمه',
        'product' => 'دفايه جامبو',
        'quantity' => '1',
        'unit_price' => '140',
        'total' => 140.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 39,
        'date' => '2025-10-05',
        'customer_name' => 'ماما هدي',
        'product' => 'ترنج ميني بيبي',
        'quantity' => '1',
        'unit_price' => '110',
        'total' => 110.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 40,
        'date' => '2025-10-05',
        'customer_name' => 'عميل محل',
        'product' => '(749) 3 + دفايه بيبي + دفايه تايجر',
        'quantity' => '3',
        'unit_price' => '160+100+140',
        'total' => 400.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 41,
        'date' => '2025-10-05',
        'customer_name' => 'عميل محل (ام احمد)',
        'product' => '(795) 10  +(780) 12 +(6007) + دفايه جامبو + دفايه بناتي +دفايه حريمي',
        'quantity' => '6',
        'unit_price' => '140',
        'total' => 140.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 42,
        'date' => '2025-10-05',
        'customer_name' => 'زميله هبه',
        'product' => 'دفايه تايجر',
        'quantity' => '1',
        'unit_price' => '140',
        'total' => 140.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 43,
        'date' => '2025-10-07',
        'customer_name' => 'زمبلة نسمه',
        'product' => 'ترنج بناتي  + (752) 18',
        'quantity' => '1',
        'unit_price' => '325',
        'total' => 325.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 44,
        'date' => '2025-10-07',
        'customer_name' => 'مني شوقي هبه',
        'product' => 'ترنج (749)',
        'quantity' => '1',
        'unit_price' => '320',
        'total' => 320.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 45,
        'date' => '2025-10-07',
        'customer_name' => 'مني حسن هبه',
        'product' => '(6007) 10 + (3010) 8 + دفايه بناتي',
        'quantity' => '3',
        'unit_price' => '345+240+120',
        'total' => 700.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 46,
        'date' => '2025-10-07',
        'customer_name' => 'اسماء  هبه',
        'product' => '(780) 16 + (752) 16 + (746) 18',
        'quantity' => '3',
        'unit_price' => '315+315+325',
        'total' => 950.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 47,
        'date' => '2025-10-07',
        'customer_name' => 'ام زين',
        'product' => '(3209) 4 + (739) 12 +(780) 14+ كورة البعبع',
        'quantity' => '4',
        'unit_price' => '220+320+315+145',
        'total' => 1000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 48,
        'date' => '2025-10-12',
        'customer_name' => 'عميل محل (فلسطين)',
        'product' => '2*130 6 +(799) 6 + (799) 6 + (799) 6 + (788) 6 + (795) 8 + (6007) 10',
        'quantity' => '6',
        'unit_price' => '250+250+250+225+250+345',
        'total' => 1830.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 49,
        'date' => '2025-10-12',
        'customer_name' => 'عميل محل (ام عبده)',
        'product' => '(752) 12+ دفاية جامبو + دفايه بناتي',
        'quantity' => '3',
        'unit_price' => '325+140+120',
        'total' => 585.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 50,
        'date' => '2025-10-12',
        'customer_name' => 'ادهم مصنع شبرا',
        'product' => 'بضاعه دفايات رجالي',
        'quantity' => '100',
        'unit_price' => null,
        'total' => -10600.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 51,
        'date' => '2025-10-13',
        'customer_name' => 'زميله نسمه',
        'product' => 'كورة البعبع',
        'quantity' => '3',
        'unit_price' => '145+175+175',
        'total' => 495.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 52,
        'date' => '2025-10-13',
        'customer_name' => 'محمد ابو الحمد',
        'product' => '(752) 18 + (780) 18 + 3 دفايه رجالي + 2 دفايه تايجر + ترنجين رجالي + 4 شروال',
        'quantity' => '13',
        'unit_price' => '325+315+140+140+600+370+370+270+270+270+270',
        'total' => 2500.0,
        'notes' => '800',
    ],
    [
        'transaction_number' => 53,
        'date' => '2025-10-13',
        'customer_name' => 'اماني صابر هبه',
        'product' => 'دفايه صبياني',
        'quantity' => '1',
        'unit_price' => '130',
        'total' => 130.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 54,
        'date' => '2025-10-13',
        'customer_name' => 'عميل محل (ام احمد)',
        'product' => '(746) 16 + (739) 18',
        'quantity' => '4',
        'unit_price' => '370+370+320+120',
        'total' => 1080.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 55,
        'date' => '2025-10-13',
        'customer_name' => 'اسماء نسمه',
        'product' => 'دفايه pink',
        'quantity' => '1',
        'unit_price' => '140',
        'total' => 140.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 56,
        'date' => '2025-10-13',
        'customer_name' => 'مي نسمه',
        'product' => 'دفايه تايجر',
        'quantity' => '1',
        'unit_price' => '140',
        'total' => 140.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 57,
        'date' => '2025-10-13',
        'customer_name' => 'عميل محل',
        'product' => 'دفايه جامبو + (8006) 3 + (8010) 3 + سلوبته',
        'quantity' => '4',
        'unit_price' => '140+315+310+160',
        'total' => 925.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 58,
        'date' => '2025-10-14',
        'customer_name' => 'عميل محل (ابو عبده)',
        'product' => '(3010) 12 + دفايه 12 + (795) 10',
        'quantity' => '3',
        'unit_price' => '240+100+250',
        'total' => 590.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 59,
        'date' => '2025-10-14',
        'customer_name' => 'عميل محل (ام احمد)',
        'product' => '(739) 16 + (795) 8',
        'quantity' => '2',
        'unit_price' => '320+250',
        'total' => 550.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 60,
        'date' => '2025-10-14',
        'customer_name' => 'عميل محل (ام حنين)',
        'product' => '(789) 10 + سلوبته',
        'quantity' => '2',
        'unit_price' => '240+160',
        'total' => 400.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 61,
        'date' => '2025-10-15',
        'customer_name' => 'عميل اونلاين (منشيه)',
        'product' => '130+130',
        'quantity' => '2',
        'unit_price' => '130+130',
        'total' => 260.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 62,
        'date' => '2025-10-15',
        'customer_name' => 'عميل محل (فلسطين)',
        'product' => '7 دفايات + يوني كورن 6 + (799) 4 + (3103) 5 + (3103) 2 + (820) 4 + (3106) 5',
        'quantity' => '13',
        'unit_price' => '700+240+250+220+220+245+130+210',
        'total' => 2170.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 63,
        'date' => '2025-10-15',
        'customer_name' => 'عميل محل',
        'product' => '(3010) 10 + (4104) 5 + دفاية 12',
        'quantity' => '3',
        'unit_price' => '240+210+100',
        'total' => 550.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 64,
        'date' => '2025-10-15',
        'customer_name' => 'احمد السيد',
        'product' => 'دفاية 8 + ترنج LC',
        'quantity' => '2',
        'unit_price' => '100+300',
        'total' => 400.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 65,
        'date' => '2025-10-15',
        'customer_name' => 'بسيطه هبه',
        'product' => '2 دفايه',
        'quantity' => '2',
        'unit_price' => '100+100',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 66,
        'date' => '2025-10-15',
        'customer_name' => 'بضاعة الرحاب',
        'product' => 'بضاعة ترنجات',
        'quantity' => '24',
        'unit_price' => null,
        'total' => -7190.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 67,
        'date' => '2025-10-17',
        'customer_name' => 'خالتي زينب',
        'product' => '2 ترنج رجالي (xl+3xl)',
        'quantity' => '1',
        'unit_price' => '370',
        'total' => 370.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 68,
        'date' => '2025-10-18',
        'customer_name' => 'بضاعة جسرالسويس',
        'product' => 'ترنجات محيرات',
        'quantity' => '36',
        'unit_price' => null,
        'total' => -6540.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 69,
        'date' => '2025-10-19',
        'customer_name' => 'اسلام نسمه',
        'product' => '٢ دفايه كمثري',
        'quantity' => '2',
        'unit_price' => '140+140',
        'total' => 280.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 70,
        'date' => '2025-10-19',
        'customer_name' => 'امل محمود',
        'product' => '(8008) + (4234) 2 + دفايه 10 + 2 سلوبته فراوله',
        'quantity' => '5',
        'unit_price' => '315+175+120+160',
        'total' => 770.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 71,
        'date' => '2025-10-19',
        'customer_name' => 'عميل محل',
        'product' => 'وتربروف + (820) 8',
        'quantity' => '2',
        'unit_price' => '275+245',
        'total' => 520.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 72,
        'date' => '2025-10-19',
        'customer_name' => 'احمد زناتي',
        'product' => 'دفايه 3xl',
        'quantity' => '4',
        'unit_price' => '180',
        'total' => 180.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 73,
        'date' => '2025-10-19',
        'customer_name' => 'ام شمس',
        'product' => '(820) 6 + (799) 6 + (741) 18',
        'quantity' => '3',
        'unit_price' => '245+250+325',
        'total' => 495.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 74,
        'date' => '2025-10-19',
        'customer_name' => 'عميل محل (اسر)',
        'product' => '(746) 18 +(741) 18 + (752) 18',
        'quantity' => '3',
        'unit_price' => '300+325+325',
        'total' => 950.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 75,
        'date' => '2025-10-20',
        'customer_name' => 'احمد عابد',
        'product' => 'ترنج رجالي+ 2 دفاية رجال + 3 دفاية اولادي + 2 دفاية اولادي + ترنج اولادي',
        'quantity' => '9',
        'unit_price' => '370+400+360+240+220',
        'total' => 1590.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 76,
        'date' => '2025-10-20',
        'customer_name' => 'مستلزمات محل بلاستك',
        'product' => 'شنط + بخور',
        'quantity' => '2',
        'unit_price' => '60+60+40',
        'total' => -140.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 77,
        'date' => '2025-10-20',
        'customer_name' => 'سعاد نسمه',
        'product' => '(788) 8 + (3406) 6',
        'quantity' => '2',
        'unit_price' => '225+240',
        'total' => 465.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 78,
        'date' => '2025-10-20',
        'customer_name' => 'عميل محل (الشرقيه)',
        'product' => '4 ترنجات + 3 بعبع + (820) 6 + 2 ترنج',
        'quantity' => '10',
        'unit_price' => '500+435+430+245',
        'total' => 1580.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 79,
        'date' => '2025-10-20',
        'customer_name' => 'عميل محل (ابو بلال)',
        'product' => 'شروال اسود + 2 ترنج  + دفايات 2xl + دفايه حريمي + 3xl + (3405)',
        'quantity' => '7',
        'unit_price' => '370+370+370+250+140+240',
        'total' => 1740.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 80,
        'date' => '2025-10-20',
        'customer_name' => 'بضاعة المليونير',
        'product' => 'دفايات',
        'quantity' => '78',
        'unit_price' => null,
        'total' => -5400.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 81,
        'date' => '2025-10-20',
        'customer_name' => 'عميل محل (ام حمزه)',
        'product' => '(8008) 4 + 2 ترنج رجالي',
        'quantity' => '3',
        'unit_price' => '370+370+315',
        'total' => 1050.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 82,
        'date' => '2025-10-20',
        'customer_name' => 'عميل محل (اسر)',
        'product' => '(749) 16 + (3010) 10 + ترنج 2',
        'quantity' => '3',
        'unit_price' => '320+240+215',
        'total' => 770.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 83,
        'date' => '2025-10-20',
        'customer_name' => 'عميل محل (ابو بلال)',
        'product' => 'دفايه تايجر + 10 (788)',
        'quantity' => '2',
        'unit_price' => '140 + 225',
        'total' => 365.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 84,
        'date' => '2025-10-21',
        'customer_name' => 'عميل محل (باع)',
        'product' => 'ترنج مقاس 2',
        'quantity' => '1',
        'unit_price' => '220',
        'total' => 220.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 85,
        'date' => '2025-10-21',
        'customer_name' => 'عميل محل (اسر)',
        'product' => '(3404) 12',
        'quantity' => '1',
        'unit_price' => '250',
        'total' => 250.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 86,
        'date' => '2025-10-21',
        'customer_name' => 'عميل محل (ماما)',
        'product' => '2 دفايه',
        'quantity' => '2',
        'unit_price' => '140+140',
        'total' => 280.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 87,
        'date' => '2025-10-21',
        'customer_name' => 'احمد السيد',
        'product' => 'دفايه 8 + دفايه جامبو',
        'quantity' => '2',
        'unit_price' => '100+140',
        'total' => 220.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 88,
        'date' => '2025-10-21',
        'customer_name' => 'عميل محل (غزل)',
        'product' => 'تيشرتين + 2 شروال + 2 دفايه جامبو + دفايه',
        'quantity' => '12',
        'unit_price' => '700+700+100+280+650+250+240+345',
        'total' => 3265.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 89,
        'date' => '2025-10-22',
        'customer_name' => 'بضاعة الرحاب',
        'product' => 'بضاعة ترنجات',
        'quantity' => '12',
        'unit_price' => null,
        'total' => -3365.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 90,
        'date' => '2025-10-22',
        'customer_name' => 'جيهان',
        'product' => '2 دفايه 12 + 2 دفايه حريمي',
        'quantity' => '4',
        'unit_price' => '120+120+140+450',
        'total' => 830.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 91,
        'date' => '2025-10-22',
        'customer_name' => 'عميل محل',
        'product' => 'دفايه 12',
        'quantity' => '1',
        'unit_price' => '120',
        'total' => 120.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 92,
        'date' => '2025-10-22',
        'customer_name' => 'خالد زناتي',
        'product' => '2 دفايه 3xl  + ترنج غطس 3xl',
        'quantity' => '3',
        'unit_price' => '180+180+350',
        'total' => 700.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 93,
        'date' => '2025-10-22',
        'customer_name' => 'لؤي عميل اونلاين',
        'product' => '2 ترنج غطس',
        'quantity' => '2',
        'unit_price' => '370+370',
        'total' => 735.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 94,
        'date' => '2025-10-22',
        'customer_name' => 'مجدي عيسي عميل اونلاين',
        'product' => '3 ترنجات اطفال  + 3 دفايات رجالي',
        'quantity' => '6',
        'unit_price' => '160+130+210+600',
        'total' => 1100.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 95,
        'date' => '2025-10-22',
        'customer_name' => 'مي سودافي عميل اونلاين',
        'product' => '2 دفايه بناتي + 2 دفايه اولادي + ٢ دفايه رجالي 3xl',
        'quantity' => '7',
        'unit_price' => '250+240+400',
        'total' => 890.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 96,
        'date' => '2025-10-23',
        'customer_name' => 'بضاعه لورد كيدز',
        'product' => 'ترنجات',
        'quantity' => '36',
        'unit_price' => null,
        'total' => -13800.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 97,
        'date' => '2025-10-23',
        'customer_name' => 'عميل محل',
        'product' => 'سلوبته فروله',
        'quantity' => '1',
        'unit_price' => '160',
        'total' => 160.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 98,
        'date' => '2025-10-23',
        'customer_name' => 'عميل محل (ام حمزه)',
        'product' => '(799) 8 +(752) 12',
        'quantity' => '2',
        'unit_price' => '250+325',
        'total' => 570.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 99,
        'date' => '2025-10-23',
        'customer_name' => 'زميل هبه',
        'product' => '2 دفايه رجالي + دفايه اولادي',
        'quantity' => '3',
        'unit_price' => '200+200+130',
        'total' => 530.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 100,
        'date' => '2025-10-23',
        'customer_name' => 'عميل محل (ام حمزه)',
        'product' => '3 دفايه جامبو +(3010) 8 + (746) 16',
        'quantity' => '5',
        'unit_price' => '450+240+315',
        'total' => 1000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 101,
        'date' => '2025-10-24',
        'customer_name' => 'عميل محل (غزل)',
        'product' => '(780) 14 + (4306) 8',
        'quantity' => '2',
        'unit_price' => '300+240',
        'total' => 500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 102,
        'date' => '2025-10-24',
        'customer_name' => 'عميل محل',
        'product' => 'ترنج اطفالي 2',
        'quantity' => '1',
        'unit_price' => '230',
        'total' => 230.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 103,
        'date' => '2025-10-24',
        'customer_name' => 'ايه زناتي',
        'product' => 'دفايه عرايس + 4 دفايات صبياني',
        'quantity' => '5',
        'unit_price' => '100+100+160+120',
        'total' => 480.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 104,
        'date' => '2025-10-24',
        'customer_name' => 'عميل محل (ام امل)',
        'product' => 'دفايه رجالي +دفايه بناتي + دفايه جامبو +(749) 10 + (795) 4',
        'quantity' => '5',
        'unit_price' => '200+120+140+220+250',
        'total' => 900.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 105,
        'date' => '2025-10-24',
        'customer_name' => 'عميل محل (ام حمزه)',
        'product' => '(627) 14 + دفايه جامبو',
        'quantity' => '2',
        'unit_price' => '580+150',
        'total' => 730.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 106,
        'date' => '2025-10-25',
        'customer_name' => 'هبه السيد',
        'product' => '(752) 14 + (780) 14',
        'quantity' => '2',
        'unit_price' => '300+300',
        'total' => 600.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 107,
        'date' => '2025-10-25',
        'customer_name' => 'عميل محل (ام حمزه)',
        'product' => '(627) 14 + (627) 14 + ترنج رجالي 2 + دفايه جامبو 2+ (3404) 8',
        'quantity' => '8',
        'unit_price' => '250+580+370+370+150',
        'total' => 1720.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 108,
        'date' => '2025-10-26',
        'customer_name' => 'بضاعة عبد الحي',
        'product' => 'بضاعة',
        'quantity' => '48',
        'unit_price' => null,
        'total' => -14000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 109,
        'date' => '2025-10-26',
        'customer_name' => 'زميل هبه',
        'product' => 'دفاية صبياني',
        'quantity' => '1',
        'unit_price' => '130',
        'total' => 130.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 110,
        'date' => '2025-10-27',
        'customer_name' => 'منه عبدالسلام',
        'product' => 'دفايه صبياني',
        'quantity' => '1',
        'unit_price' => '120',
        'total' => 120.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 111,
        'date' => '2025-10-28',
        'customer_name' => 'ماما',
        'product' => 'دفايه جامبو + دفايه بناتي',
        'quantity' => '2',
        'unit_price' => '80+100',
        'total' => 180.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 112,
        'date' => '2025-10-30',
        'customer_name' => 'إيجار المحل',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -1500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 113,
        'date' => '2025-10-31',
        'customer_name' => 'محمد السيد',
        'product' => '2 سنجاب + (4234) 3 + (798) 6 + 2 كوره البعبع',
        'quantity' => '6',
        'unit_price' => '480+175+380+145+175',
        'total' => 1350.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 114,
        'date' => '2025-11-02',
        'customer_name' => 'عميل محل',
        'product' => '(741) 12 + ترنج رجالي',
        'quantity' => '2',
        'unit_price' => '370+325',
        'total' => 695.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 115,
        'date' => '2025-11-03',
        'customer_name' => 'عميل محل',
        'product' => '(8008) 4+(820) 6+(8010) 4',
        'quantity' => '3',
        'unit_price' => '315+245+315+250',
        'total' => 860.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 116,
        'date' => '2025-11-03',
        'customer_name' => 'عميل اونلاين (ندي)',
        'product' => 'ترنج اطفالي + 2 ترنج قطن + 2 ترنج اولادي',
        'quantity' => '5',
        'unit_price' => '110+110+1100+500',
        'total' => 1760.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 117,
        'date' => '2025-11-03',
        'customer_name' => 'عميل اونلاين (ندي)',
        'product' => '2 دفايه رجالي + 3 دفايه حريمي',
        'quantity' => '5',
        'unit_price' => '200+200+140+140',
        'total' => 680.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 118,
        'date' => '2025-11-05',
        'customer_name' => 'عميل اونلاين (محمد شعبان)',
        'product' => '3 ترنجات',
        'quantity' => '3',
        'unit_price' => '315+580+250',
        'total' => 1120.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 119,
        'date' => '2025-11-05',
        'customer_name' => 'عميل اونلاين (مريم محمد )',
        'product' => '2 دفايه رجالي + ترنج',
        'quantity' => '2',
        'unit_price' => '400+230',
        'total' => 615.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 120,
        'date' => '2025-11-05',
        'customer_name' => 'عميل اونلاين (محمد الضبع)',
        'product' => '6 ترنجات',
        'quantity' => '6',
        'unit_price' => '295+240+220+250',
        'total' => 1555.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 121,
        'date' => '2025-11-06',
        'customer_name' => 'عميل اونلاين (ندي)',
        'product' => '2 ترنج بناتي + ترنج رجالي',
        'quantity' => '3',
        'unit_price' => '315+325+370',
        'total' => 1010.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 122,
        'date' => '2025-11-09',
        'customer_name' => 'جمال زميل هبه',
        'product' => 'ترنجين L',
        'quantity' => '2',
        'unit_price' => '370+370+370',
        'total' => 1100.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 123,
        'date' => '2025-11-09',
        'customer_name' => 'زميله هبه',
        'product' => '3 دفايات  10',
        'quantity' => '3',
        'unit_price' => '120+120+120',
        'total' => 360.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 124,
        'date' => '2025-11-09',
        'customer_name' => 'عميل محل (ام عبير)',
        'product' => '2 دفايه 12 + ترنج (750) 12',
        'quantity' => '3',
        'unit_price' => '120+120+450',
        'total' => 690.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 125,
        'date' => '2025-11-10',
        'customer_name' => 'عميل محل (ام احمد سهير)',
        'product' => '3 ترنجات 110 + ترنج 220 +ترنج 130',
        'quantity' => '6',
        'unit_price' => '110+110+110+130+220',
        'total' => 680.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 126,
        'date' => '2025-11-11',
        'customer_name' => 'زميله هبه',
        'product' => 'ترنج رجالي 2xl',
        'quantity' => '1',
        'unit_price' => '370',
        'total' => 370.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 127,
        'date' => '2025-11-11',
        'customer_name' => 'ماما هدي',
        'product' => 'سلوبته + ترنج حور',
        'quantity' => '2',
        'unit_price' => '150+220',
        'total' => 370.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 128,
        'date' => '2025-11-12',
        'customer_name' => 'عميل محل',
        'product' => '(6002) 10 + (3406) 10 +(752) 12 +(6007) 12 + (750) 10',
        'quantity' => '5',
        'unit_price' => '320+240+325+345+430',
        'total' => 1660.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 129,
        'date' => '2025-11-12',
        'customer_name' => 'عميل اونلاين',
        'product' => 'ترنجات اطفال + بناتي + 2 ترنجات رجالي',
        'quantity' => '12',
        'unit_price' => '440+300+370+350+310+220+450+740+280',
        'total' => 3425.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 130,
        'date' => '2025-11-12',
        'customer_name' => 'ايه زناتي',
        'product' => 'ترنجين',
        'quantity' => '2',
        'unit_price' => '215+210',
        'total' => 425.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 131,
        'date' => '2025-11-12',
        'customer_name' => 'عميل محل (هويده)',
        'product' => '(3106)  + (4104) + (786) + (629) + (820) + (8008) + قطه + دفايتين',
        'quantity' => '10',
        'unit_price' => '210+215+220+210+450+245+200+315',
        'total' => 2265.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 132,
        'date' => '2025-11-16',
        'customer_name' => 'عميل اونلاين',
        'product' => 'ترنجات مقاس 6',
        'quantity' => '5',
        'unit_price' => '250+225+250+245+580',
        'total' => 1550.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 133,
        'date' => '2025-11-16',
        'customer_name' => 'عميل محل (دينا)',
        'product' => '(789) 10 + (6007) 8 +(750) 8+(3010) 6 + دفايتن 10',
        'quantity' => '6',
        'unit_price' => '220+345+430+240+120+120',
        'total' => 1130.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 134,
        'date' => '2025-11-16',
        'customer_name' => 'بضاعة دلعين',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -17250.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 135,
        'date' => '2025-11-18',
        'customer_name' => 'عميل اونلاين (احمد شعبان )',
        'product' => 'ترنجين',
        'quantity' => '2',
        'unit_price' => '300+300',
        'total' => 600.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 136,
        'date' => '2025-11-18',
        'customer_name' => 'عميل اونلاين (ايناس)',
        'product' => 'ترنجات',
        'quantity' => '5',
        'unit_price' => null,
        'total' => 1924.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 137,
        'date' => '2025-11-18',
        'customer_name' => 'ماما',
        'product' => 'ترنج 3xl',
        'quantity' => '1',
        'unit_price' => null,
        'total' => 350.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 138,
        'date' => '2025-11-18',
        'customer_name' => 'زميله هبه',
        'product' => 'ترنج 2xl',
        'quantity' => '1',
        'unit_price' => null,
        'total' => 350.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 139,
        'date' => '2025-11-18',
        'customer_name' => 'عميل محل',
        'product' => 'ترنج 14',
        'quantity' => '1',
        'unit_price' => '320',
        'total' => 320.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 140,
        'date' => '2025-11-18',
        'customer_name' => 'هبه',
        'product' => '4 طقم داخلي اولادي 10',
        'quantity' => '4',
        'unit_price' => '110*4',
        'total' => 440.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 141,
        'date' => '2025-11-18',
        'customer_name' => 'عميل اونلاين (ايناس)',
        'product' => 'ترنج l',
        'quantity' => '2',
        'unit_price' => '370+370',
        'total' => 740.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 142,
        'date' => '2025-11-18',
        'customer_name' => 'احمد السيد',
        'product' => 'طقم داخلي',
        'quantity' => '2',
        'unit_price' => '180+100',
        'total' => 280.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 143,
        'date' => '2025-11-24',
        'customer_name' => 'عميل محل (ام وعد)',
        'product' => '4 ترنجات حريمي + 3 بجامات زراير',
        'quantity' => '7',
        'unit_price' => '2200+1260',
        'total' => 3460.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 144,
        'date' => '2025-11-24',
        'customer_name' => 'ايه زناتي',
        'product' => '2 دفايه عرايس + دفايه حريمي + سلوبته + دفايه اطفال +ترنج حريمي + ترنج ١٣٠',
        'quantity' => '7',
        'unit_price' => '140+140+150+125+100+550+130',
        'total' => 1000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 145,
        'date' => '2025-11-24',
        'customer_name' => 'عميل محل (ام وعد)',
        'product' => '3 بجامات زراير +  2 ترنج حريمي',
        'quantity' => '5',
        'unit_price' => '1290+1100',
        'total' => 2390.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 146,
        'date' => '2025-11-24',
        'customer_name' => 'عميل اونلاين (ناير نبيل)',
        'product' => 'ترنجات + دفايه',
        'quantity' => '5',
        'unit_price' => null,
        'total' => 1365.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 147,
        'date' => '2025-11-25',
        'customer_name' => 'بضاعة بيجامتك',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -15000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 148,
        'date' => '2025-11-25',
        'customer_name' => 'إيجار المحل',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -1500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 149,
        'date' => '2025-11-26',
        'customer_name' => 'عميل محل (ام وعد)',
        'product' => '3 ترنجات حريمي',
        'quantity' => '3',
        'unit_price' => '550+550+550',
        'total' => 1650.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 150,
        'date' => '2025-11-26',
        'customer_name' => 'زميل هبه',
        'product' => '3 دفايات رجالي',
        'quantity' => '3',
        'unit_price' => '200*3',
        'total' => 600.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 151,
        'date' => '2025-11-27',
        'customer_name' => 'دينا (ام احمد سهير)',
        'product' => '(6002) 6 +(4305) 6+ (3406) 6+ وتربروف',
        'quantity' => '4',
        'unit_price' => '240+240+320+275',
        'total' => 1075.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 152,
        'date' => '2025-11-27',
        'customer_name' => 'عميل محل',
        'product' => 'ترنج بناتي 12',
        'quantity' => '1',
        'unit_price' => '315',
        'total' => 315.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 153,
        'date' => '2025-11-27',
        'customer_name' => 'ام احمد النجوم',
        'product' => '2 ترنج 746',
        'quantity' => '2',
        'unit_price' => '315+315',
        'total' => 630.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 154,
        'date' => '2025-11-27',
        'customer_name' => 'ام وعد',
        'product' => '3 ترنجات 4xl',
        'quantity' => '3',
        'unit_price' => '550+550+550',
        'total' => 1650.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 155,
        'date' => '2025-11-27',
        'customer_name' => 'دينا (ام احمد سهير)',
        'product' => '2 ترنج زراير + 2 دفايه حريمي',
        'quantity' => '3',
        'unit_price' => '430+140+140',
        'total' => 700.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 156,
        'date' => '2025-11-27',
        'customer_name' => 'عميل محل',
        'product' => '2 دفايه صبياني +  دفايه حريمي',
        'quantity' => '3',
        'unit_price' => '200+130',
        'total' => 330.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 157,
        'date' => '2025-11-29',
        'customer_name' => 'عميل محل',
        'product' => 'ترنج اطفالي ١',
        'quantity' => '1',
        'unit_price' => '130',
        'total' => 130.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 158,
        'date' => '2025-11-30',
        'customer_name' => 'ناديه نسمه',
        'product' => '4 ترنجات حريمي  + باكيت اندر',
        'quantity' => '5',
        'unit_price' => '550+550+550+180+550',
        'total' => 2380.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 159,
        'date' => '2025-11-30',
        'customer_name' => 'عميل محل (ام فهد)',
        'product' => '3 دفايه حريمي',
        'quantity' => '3',
        'unit_price' => '140+140+140',
        'total' => 420.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 160,
        'date' => '2025-12-02',
        'customer_name' => 'عميل محل',
        'product' => 'دفاتين',
        'quantity' => '1',
        'unit_price' => '200',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 161,
        'date' => '2025-12-03',
        'customer_name' => 'محمد السيد',
        'product' => '6 حماله رجالي 2 xl',
        'quantity' => '6',
        'unit_price' => '95*6',
        'total' => 570.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 162,
        'date' => '2025-12-03',
        'customer_name' => 'ابراهيم موبايل',
        'product' => 'ترنج قطن + ترنج بوب كورن 12',
        'quantity' => '2',
        'unit_price' => '550+450',
        'total' => 1000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 163,
        'date' => '2025-12-03',
        'customer_name' => 'بضاعة دلعين',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -3750.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 164,
        'date' => '2025-12-03',
        'customer_name' => 'هبه السيد',
        'product' => '4 بوكسر 3xl + جينز + اسدال',
        'quantity' => '6',
        'unit_price' => '300+350+300',
        'total' => 950.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 165,
        'date' => '2025-12-04',
        'customer_name' => 'نوره هبه',
        'product' => 'ترنج اطفالي',
        'quantity' => '1',
        'unit_price' => '250',
        'total' => 250.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 166,
        'date' => '2025-12-03',
        'customer_name' => 'ياسر مسعد',
        'product' => '6 طقم داخلي xL و بوكسر 2xl',
        'quantity' => '6',
        'unit_price' => '160*6',
        'total' => 960.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 167,
        'date' => '2025-12-03',
        'customer_name' => 'ام عبده',
        'product' => 'دفايه 12 + ترنج 14 +ترنج 16+سويت تيشرت',
        'quantity' => '4',
        'unit_price' => '120+200+315+320',
        'total' => 950.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 168,
        'date' => '2025-12-04',
        'customer_name' => 'جيهان',
        'product' => 'بوكسر 3xl + 2xl + xl+ دفايه حريمي',
        'quantity' => '3',
        'unit_price' => '85+85+85',
        'total' => 250.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 169,
        'date' => '2025-12-04',
        'customer_name' => 'عميل محل',
        'product' => 'دفايه رجالي  xl',
        'quantity' => '1',
        'unit_price' => '200',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 170,
        'date' => '2025-12-05',
        'customer_name' => 'ابراهيم موبايل',
        'product' => '4 طقم داخلي + بوكسر + ترنجين 10 و 12',
        'quantity' => '7',
        'unit_price' => '550+450+400+85',
        'total' => 1450.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 171,
        'date' => '2025-12-07',
        'customer_name' => 'عميل محل (ام فهد)',
        'product' => '4 بنطلون + 2 باكيت داخلي + 6 دفايه + 3 دفايه',
        'quantity' => '15',
        'unit_price' => '260+360+900+450',
        'total' => 1970.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 172,
        'date' => '2025-12-07',
        'customer_name' => 'عميل محل (ام فهد)',
        'product' => '3 دفايه + ترنج 5xl + 4 طقم داخلي',
        'quantity' => '8',
        'unit_price' => '420+550+720',
        'total' => 1690.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 173,
        'date' => '2025-12-07',
        'customer_name' => 'نسمه خالد',
        'product' => 'سويت تيشرت + ترنج 5xl+بوكسر+4طقم داخلي',
        'quantity' => '7',
        'unit_price' => '200+550+400+85',
        'total' => 1230.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 174,
        'date' => '2025-12-07',
        'customer_name' => 'ماما',
        'product' => '3 جينز',
        'quantity' => '3',
        'unit_price' => '1000',
        'total' => 1000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 175,
        'date' => '2025-12-07',
        'customer_name' => 'بضاعه حبيبه تكس',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -19200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 176,
        'date' => '2025-12-08',
        'customer_name' => 'ام فهد',
        'product' => '3 طقم داخلي 3xl',
        'quantity' => '3',
        'unit_price' => '180+180+180',
        'total' => 540.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 177,
        'date' => '2025-12-08',
        'customer_name' => 'ام فريده',
        'product' => 'ترنجات بناتي',
        'quantity' => '2',
        'unit_price' => '325+370+225',
        'total' => 920.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 178,
        'date' => '2025-12-09',
        'customer_name' => 'ام فهد',
        'product' => '3 اسدال',
        'quantity' => '3',
        'unit_price' => '370+370+370',
        'total' => 1100.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 179,
        'date' => '2025-12-10',
        'customer_name' => 'عميل محل (ام عمار)',
        'product' => '2 ترنج 5',
        'quantity' => '2',
        'unit_price' => '215+310',
        'total' => 525.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 180,
        'date' => '2025-12-10',
        'customer_name' => 'نسمه خالد',
        'product' => 'دفايه رجالي',
        'quantity' => '1',
        'unit_price' => '200',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 181,
        'date' => '2025-12-10',
        'customer_name' => 'ام عامر بريد',
        'product' => 'ترنج 12 بناتي',
        'quantity' => '1',
        'unit_price' => '325+370',
        'total' => 695.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 182,
        'date' => '2025-12-14',
        'customer_name' => 'عميل محل',
        'product' => 'سويت تيشرت 12',
        'quantity' => '1',
        'unit_price' => '200',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 183,
        'date' => '2025-12-15',
        'customer_name' => 'احمد زناتي',
        'product' => 'دفايه رجالي 3xl',
        'quantity' => '1',
        'unit_price' => '180',
        'total' => 180.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 184,
        'date' => '2025-12-16',
        'customer_name' => 'ماما',
        'product' => 'دفايه 2 + 3 هودي',
        'quantity' => '5',
        'unit_price' => '400+480+480+480',
        'total' => 1800.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 185,
        'date' => '2025-12-16',
        'customer_name' => 'ام منه',
        'product' => '3 بجامه زراير + 2 اندر + اسدال +  باكيت اندر+ بجامه زراير',
        'quantity' => '6',
        'unit_price' => '430+430+120+370+430+180',
        'total' => 1570.0,
        'notes' => '390+180=570',
    ],
    [
        'transaction_number' => 186,
        'date' => '2025-12-16',
        'customer_name' => 'هبه السيد',
        'product' => 'هودي + بنطلون جينز',
        'quantity' => '4',
        'unit_price' => '450+350+450+300',
        'total' => 1700.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 187,
        'date' => '2025-12-16',
        'customer_name' => 'بضاعة مصنع باريس',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -9300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 188,
        'date' => '2025-12-16',
        'customer_name' => 'عميل محل',
        'product' => 'ترنج بناتي',
        'quantity' => '1',
        'unit_price' => '220',
        'total' => 220.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 189,
        'date' => '2025-12-15',
        'customer_name' => 'عميل اونلاين',
        'product' => 'بجامه حريمي',
        'quantity' => '1',
        'unit_price' => '515',
        'total' => 515.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 190,
        'date' => '2025-12-16',
        'customer_name' => 'عميل محل',
        'product' => 'ترنجين',
        'quantity' => '2',
        'unit_price' => '550',
        'total' => 550.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 191,
        'date' => '2025-12-17',
        'customer_name' => 'ابراهيم موبايل',
        'product' => 'بوكسر+ بنطلون + دفاية',
        'quantity' => '3',
        'unit_price' => '85+400+200',
        'total' => 650.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 192,
        'date' => '2025-12-18',
        'customer_name' => 'حنان خالد',
        'product' => 'دفايه',
        'quantity' => '1',
        'unit_price' => '200',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 193,
        'date' => '2025-12-21',
        'customer_name' => 'ابو بلال',
        'product' => '2 دفايه',
        'quantity' => '2',
        'unit_price' => '200+100',
        'total' => 300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 194,
        'date' => '2025-12-21',
        'customer_name' => 'محمد السيد',
        'product' => 'سويتتيشرت 2 + بجامه حريمي',
        'quantity' => '3',
        'unit_price' => '480+480+430',
        'total' => 1390.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 195,
        'date' => '2025-12-22',
        'customer_name' => 'عميل محل',
        'product' => 'دفايه حريمي + دفايه رجالي',
        'quantity' => '2',
        'unit_price' => '180+150',
        'total' => 330.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 196,
        'date' => '2025-12-22',
        'customer_name' => 'ام فهد',
        'product' => '8 دفايات حريمي + 6 بنطلون حريمي',
        'quantity' => '14',
        'unit_price' => '1200+390',
        'total' => 1590.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 197,
        'date' => '2025-12-21',
        'customer_name' => 'بضاعه حبيبه تكس',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -4312.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 198,
        'date' => '2025-12-22',
        'customer_name' => 'إيجار المحل + مرتب',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -2000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 199,
        'date' => '2025-12-22',
        'customer_name' => 'ام فهد',
        'product' => 'دفايه حريمي',
        'quantity' => '2',
        'unit_price' => '150+150',
        'total' => 300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 200,
        'date' => '2025-12-25',
        'customer_name' => 'عميل محل',
        'product' => 'دفايه بناتي + دفايه اولادي',
        'quantity' => '2',
        'unit_price' => '130+120',
        'total' => 250.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 201,
        'date' => '2025-12-25',
        'customer_name' => 'عميل اونلاين',
        'product' => 'دفايات رجالي',
        'quantity' => '2',
        'unit_price' => '180+180',
        'total' => 380.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 202,
        'date' => '2025-12-27',
        'customer_name' => 'احمد السيد',
        'product' => 'بوكسر xl',
        'quantity' => '1',
        'unit_price' => '85',
        'total' => 85.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 203,
        'date' => '2025-12-28',
        'customer_name' => 'ياسر مسعد',
        'product' => 'هودي + بنطلون جينز',
        'quantity' => '2',
        'unit_price' => '350+480',
        'total' => 830.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 204,
        'date' => '2025-12-30',
        'customer_name' => 'عميل محل',
        'product' => 'هودي',
        'quantity' => '1',
        'unit_price' => '200',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 205,
        'date' => '2025-12-30',
        'customer_name' => 'زميلة هبه',
        'product' => 'طقم خروج 5',
        'quantity' => '1',
        'unit_price' => '575',
        'total' => 575.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 206,
        'date' => '2025-12-30',
        'customer_name' => 'بضاعة مصنع باريس',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -9500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 207,
        'date' => '2025-12-30',
        'customer_name' => 'جيهان',
        'product' => 'دفاية حريمي',
        'quantity' => '1',
        'unit_price' => '150',
        'total' => 150.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 208,
        'date' => '2025-12-30',
        'customer_name' => 'ياسر مسعد',
        'product' => 'بنطلون جينز',
        'quantity' => '1',
        'unit_price' => '350',
        'total' => 350.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 209,
        'date' => '2025-12-30',
        'customer_name' => 'ام فهد',
        'product' => 'دفايتن',
        'quantity' => '2',
        'unit_price' => '150+150',
        'total' => 300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 210,
        'date' => '2025-12-31',
        'customer_name' => 'ام فهد',
        'product' => 'دفايتين',
        'quantity' => '2',
        'unit_price' => '150+150',
        'total' => 300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 211,
        'date' => '2025-12-31',
        'customer_name' => 'عميل محل (ندي)',
        'product' => 'ترنج 6 + ترنج سنجاب',
        'quantity' => '2',
        'unit_price' => '240+240',
        'total' => 480.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 212,
        'date' => '2025-12-31',
        'customer_name' => 'ام فهد',
        'product' => 'طقم خروج 14 جينز',
        'quantity' => '1',
        'unit_price' => '625',
        'total' => 625.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 213,
        'date' => '2026-01-01',
        'customer_name' => 'ام عبده',
        'product' => 'طقم خروج 10 جينز',
        'quantity' => '1',
        'unit_price' => '650',
        'total' => 650.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 214,
        'date' => '2026-01-04',
        'customer_name' => 'جيهان',
        'product' => 'هودي بيج سايز',
        'quantity' => '1',
        'unit_price' => '450',
        'total' => 450.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 215,
        'date' => '2026-01-05',
        'customer_name' => 'الشيخ خالد جاري',
        'product' => 'دفايتن + 2 بنطلون جينز',
        'quantity' => '4',
        'unit_price' => '400+350+350',
        'total' => 1100.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 216,
        'date' => '2026-01-06',
        'customer_name' => 'ايه زناتي',
        'product' => 'ترنج سنه',
        'quantity' => '1',
        'unit_price' => '230',
        'total' => 480.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 217,
        'date' => '2026-01-07',
        'customer_name' => 'هبه اختي',
        'product' => 'دفايه اولادي 12',
        'quantity' => '3',
        'unit_price' => '100+100+100',
        'total' => 300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 218,
        'date' => '2026-01-08',
        'customer_name' => 'عميل محل',
        'product' => 'سويتشيرت + ترنج 3',
        'quantity' => '2',
        'unit_price' => '370+200',
        'total' => 570.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 219,
        'date' => '2026-01-08',
        'customer_name' => 'عميل محل',
        'product' => 'بوكسر + دفايه',
        'quantity' => '2',
        'unit_price' => '200+85',
        'total' => 285.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 220,
        'date' => '2026-01-10',
        'customer_name' => 'ثناء زميله هبه',
        'product' => '2 هودي',
        'quantity' => '2',
        'unit_price' => '450',
        'total' => 450.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 221,
        'date' => '2026-01-10',
        'customer_name' => 'نورا زميله هبه',
        'product' => 'ترنج اولادي + 2 باكيت اندر',
        'quantity' => '4',
        'unit_price' => '180+180+315+100',
        'total' => 775.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 222,
        'date' => '2026-01-11',
        'customer_name' => 'الشيخ خالد',
        'product' => 'بنطلون جينز',
        'quantity' => '1',
        'unit_price' => '350',
        'total' => 350.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 223,
        'date' => '2026-01-13',
        'customer_name' => 'مني حسن زميله هبه',
        'product' => '2 باكيت اندر + هودي',
        'quantity' => '2',
        'unit_price' => '450+360',
        'total' => 810.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 224,
        'date' => '2026-01-13',
        'customer_name' => 'اميره زميله هبه',
        'product' => 'ترنج رجالي + هودي',
        'quantity' => '2',
        'unit_price' => '370+450',
        'total' => 820.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 225,
        'date' => '2026-01-13',
        'customer_name' => 'بضاعه حبيبه تكس',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -8100.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 226,
        'date' => '2026-01-14',
        'customer_name' => 'احمد السيد',
        'product' => 'هودي + اسدال',
        'quantity' => '2',
        'unit_price' => '200+430',
        'total' => 630.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 227,
        'date' => '2026-01-15',
        'customer_name' => 'هبه السيد',
        'product' => 'هودي + ترنج بناتي 4',
        'quantity' => '2',
        'unit_price' => '150+200',
        'total' => 350.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 228,
        'date' => '2026-01-15',
        'customer_name' => 'احمد السيد',
        'product' => 'هودي + دفايتن + ترنج 3 + هودي+ ترنج 2',
        'quantity' => '6',
        'unit_price' => '80+100+160+200+450+175',
        'total' => 1160.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 229,
        'date' => '2026-01-17',
        'customer_name' => 'عميل محل',
        'product' => 'سويت تيشرت 10',
        'quantity' => '1',
        'unit_price' => '200',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 230,
        'date' => '2026-01-18',
        'customer_name' => 'عميل محل',
        'product' => 'دفايه رجالي 2xl',
        'quantity' => '2',
        'unit_price' => '200+200',
        'total' => 400.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 231,
        'date' => '2026-01-20',
        'customer_name' => 'زميله ايه زناتي',
        'product' => 'دفايتن',
        'quantity' => '2',
        'unit_price' => '150+150',
        'total' => 300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 232,
        'date' => '2026-01-24',
        'customer_name' => 'بضاعه حبيبه تكس',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -1200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 233,
        'date' => '2026-01-24',
        'customer_name' => 'بضاعه جينز',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -7000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 234,
        'date' => '2026-01-25',
        'customer_name' => 'خالد احمد',
        'product' => 'اسدال',
        'quantity' => '1',
        'unit_price' => '430',
        'total' => 430.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 235,
        'date' => '2026-01-25',
        'customer_name' => 'سلمي احمد',
        'product' => '2 باكيت اندر +  4 بادي + 3 دفايه + 2 بجامه زراير + بيجامه 3xl +  اسدالين+ البنطلون',
        'quantity' => '14',
        'unit_price' => '3250',
        'total' => 1250.0,
        'notes' => '2000',
    ],
    [
        'transaction_number' => 236,
        'date' => '2026-01-26',
        'customer_name' => 'ايه زناتي',
        'product' => 'سلوبته',
        'quantity' => '1',
        'unit_price' => '160',
        'total' => 160.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 237,
        'date' => '2026-01-26',
        'customer_name' => 'احمد السيد',
        'product' => 'اسدال 2',
        'quantity' => '2',
        'unit_price' => '400+400',
        'total' => 800.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 238,
        'date' => '2026-01-27',
        'customer_name' => 'ام عبده',
        'product' => 'بنطلون جينز',
        'quantity' => '1',
        'unit_price' => '270',
        'total' => 270.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 239,
        'date' => '2026-01-28',
        'customer_name' => 'عميل المحل  ( ابتهال )',
        'product' => 'ترنجين 10 + 12',
        'quantity' => '2',
        'unit_price' => '480+250',
        'total' => 730.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 240,
        'date' => '2026-02-03',
        'customer_name' => 'عميل محل',
        'product' => 'دفايه حريمي',
        'quantity' => '1',
        'unit_price' => '150',
        'total' => 150.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 241,
        'date' => '2026-02-04',
        'customer_name' => 'عميل محل (شيخ خالد)',
        'product' => '2 دفاية رجالي (xl - L)',
        'quantity' => '2',
        'unit_price' => '180+180',
        'total' => 360.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 242,
        'date' => '2026-01-30',
        'customer_name' => 'إيجار المحل + مرتب',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -2000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 243,
        'date' => '2026-02-04',
        'customer_name' => 'بضاعه النعيم',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -1500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 244,
        'date' => '2026-02-05',
        'customer_name' => 'عميل محل',
        'product' => 'ترنج رجالي + دفايه',
        'quantity' => '2',
        'unit_price' => '200+350',
        'total' => 550.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 245,
        'date' => '2026-02-06',
        'customer_name' => 'ايمان عجلان',
        'product' => 'اندر حريمي باكيت',
        'quantity' => '3',
        'unit_price' => '180',
        'total' => 180.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 246,
        'date' => '2026-02-07',
        'customer_name' => 'ام عبده',
        'product' => '2 دفايه رجالي + ترنج L + 2 ترنج بناتي 12 + 3 دفايه مقاس 12 + 3 دفايه حريمي + اسدال',
        'quantity' => '12',
        'unit_price' => '360+350+480+300+420+400',
        'total' => 2300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 247,
        'date' => '2026-02-07',
        'customer_name' => 'ام محمد',
        'product' => '2 دفايه حريمي',
        'quantity' => '2',
        'unit_price' => '140+140',
        'total' => null,
        'notes' => '280',
    ],
    [
        'transaction_number' => 248,
        'date' => '2026-02-07',
        'customer_name' => 'ام عبده',
        'product' => 'اسدال ملحفه + هودي',
        'quantity' => '2',
        'unit_price' => '200+400',
        'total' => null,
        'notes' => '600',
    ],
    [
        'transaction_number' => 249,
        'date' => '2026-02-07',
        'customer_name' => 'عميل محل (شيخ خالد)',
        'product' => '2 دفايه حريمي + هودي xl',
        'quantity' => '3',
        'unit_price' => '150+150',
        'total' => 750.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 250,
        'date' => '2026-02-08',
        'customer_name' => 'عميل محل (شيخ خالد)',
        'product' => 'دفاية رجالي',
        'quantity' => '1',
        'unit_price' => '180',
        'total' => 180.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 251,
        'date' => '2026-02-08',
        'customer_name' => 'عميل محل',
        'product' => '2 جينز + 2 هودي + قطة',
        'quantity' => '4',
        'unit_price' => '470+270+200+210',
        'total' => 1150.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 252,
        'date' => '2026-02-10',
        'customer_name' => 'عميل محل',
        'product' => '2 طقم داخلي',
        'quantity' => '2',
        'unit_price' => '100+100',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 253,
        'date' => '2026-02-12',
        'customer_name' => 'عميل محل',
        'product' => 'جينز + هودي',
        'quantity' => '2',
        'unit_price' => '300+200',
        'total' => 500.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 254,
        'date' => '2026-02-15',
        'customer_name' => 'عميل اونلاين',
        'product' => 'هودي 2',
        'quantity' => '2',
        'unit_price' => '380',
        'total' => 380.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 255,
        'date' => '2026-02-15',
        'customer_name' => 'احمد السيد',
        'product' => 'طقم جينز 4',
        'quantity' => '1',
        'unit_price' => '550',
        'total' => 550.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 256,
        'date' => '2026-02-15',
        'customer_name' => 'الشيج جاري',
        'product' => '2 باكيت اندر + 4 بدي',
        'quantity' => '6',
        'unit_price' => '180+180+90+90+90+90',
        'total' => 700.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 257,
        'date' => '2026-02-16',
        'customer_name' => 'ايه زناتي',
        'product' => 'اسدال',
        'quantity' => '1',
        'unit_price' => '370',
        'total' => 370.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 258,
        'date' => '2026-02-16',
        'customer_name' => 'عميل محل',
        'product' => '٢ ترنج قطيفه + بداله جينز',
        'quantity' => '3',
        'unit_price' => '175+175+550',
        'total' => 900.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 259,
        'date' => '2026-02-18',
        'customer_name' => 'ايه زناتي',
        'product' => 'اسدال',
        'quantity' => '1',
        'unit_price' => '370',
        'total' => 370.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 260,
        'date' => '2026-02-18',
        'customer_name' => 'منه جارتنا',
        'product' => 'باكيت اندر',
        'quantity' => '1',
        'unit_price' => '180',
        'total' => 180.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 261,
        'date' => '2026-02-20',
        'customer_name' => 'دكتور هشام',
        'product' => 'هودي + اسدال + بجامه حريمي',
        'quantity' => '3',
        'unit_price' => '500+370+450',
        'total' => 1300.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 262,
        'date' => '2026-02-22',
        'customer_name' => 'عميل محل',
        'product' => 'اسدال',
        'quantity' => '1',
        'unit_price' => '380',
        'total' => 380.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 263,
        'date' => '2026-02-22',
        'customer_name' => 'عمر عويس',
        'product' => 'دفايه رجالي',
        'quantity' => '1',
        'unit_price' => '180',
        'total' => 180.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 264,
        'date' => '2026-02-22',
        'customer_name' => 'نورا زميله هبه',
        'product' => 'إسدال',
        'quantity' => '1',
        'unit_price' => '400',
        'total' => 200.0,
        'notes' => '200',
    ],
    [
        'transaction_number' => 265,
        'date' => '2026-02-22',
        'customer_name' => 'سلوي زميله هبه',
        'product' => 'بنطلون',
        'quantity' => '2',
        'unit_price' => '50+50',
        'total' => 100.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 266,
        'date' => '2026-02-22',
        'customer_name' => 'عبداللاه',
        'product' => 'دفايه رجالي',
        'quantity' => '1',
        'unit_price' => '160',
        'total' => 160.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 267,
        'date' => '2026-02-25',
        'customer_name' => 'زميله نسمه',
        'product' => 'ترنجين + 3 بنطلون',
        'quantity' => '5',
        'unit_price' => '350+350+150',
        'total' => 850.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 268,
        'date' => '2026-02-24',
        'customer_name' => 'بضاعه كساب',
        'product' => 'اسدالات',
        'quantity' => '24',
        'unit_price' => null,
        'total' => -6400.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 269,
        'date' => '2026-02-25',
        'customer_name' => 'إيجار المحل + مرتب',
        'product' => null,
        'quantity' => null,
        'unit_price' => null,
        'total' => -2000.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 270,
        'date' => '2026-02-25',
        'customer_name' => 'عميل محل',
        'product' => '2 سلوبته',
        'quantity' => '2',
        'unit_price' => '125+125',
        'total' => 250.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 271,
        'date' => '2026-02-25',
        'customer_name' => 'ابو بلال',
        'product' => 'بنطلون جينز +هودي 3xl + هودي + بنطلون جينز +كاش+اسدال',
        'quantity' => '7',
        'unit_price' => '350+400+270+220+200+70+360',
        'total' => 1860.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 272,
        'date' => '2026-02-26',
        'customer_name' => 'اميره زميله هبه',
        'product' => 'اسدال + ملحفه + هودي وشروال +ترنج حريمي + 2 طقم بناتي + 2 بوكسر',
        'quantity' => '9',
        'unit_price' => '350+380+350+400+500+200+170',
        'total' => null,
        'notes' => '2350',
    ],
    [
        'transaction_number' => 273,
        'date' => '2026-02-27',
        'customer_name' => 'الشيخ خالد',
        'product' => 'هودي + ترنج 8 + ترنج 14 + دفايه',
        'quantity' => '4',
        'unit_price' => '350+300+100+400',
        'total' => 1150.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 274,
        'date' => '2026-02-27',
        'customer_name' => 'احمد السيد ابو الفضل',
        'product' => 'هودي',
        'quantity' => '1',
        'unit_price' => '400',
        'total' => 400.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 275,
        'date' => '2026-02-28',
        'customer_name' => 'منه جارتنا',
        'product' => 'دفايه اطفالي',
        'quantity' => '1',
        'unit_price' => '100',
        'total' => 100.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 276,
        'date' => '2026-02-28',
        'customer_name' => 'هبه السيد',
        'product' => 'دفاييتن  عرايس',
        'quantity' => '2',
        'unit_price' => '100+100',
        'total' => 200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 277,
        'date' => '2026-03-01',
        'customer_name' => 'رانيا زميله هبه',
        'product' => 'اسدال + ترنجات + ملحمه',
        'quantity' => '12',
        'unit_price' => '400+420+370+380+300+320+300+380',
        'total' => 2870.0,
        'notes' => '200+370',
    ],
    [
        'transaction_number' => 278,
        'date' => '2026-03-02',
        'customer_name' => 'نورا زميله هبه',
        'product' => 'ترنج شبابي + بوكسر + 2 دفاية حريمي',
        'quantity' => '4',
        'unit_price' => '350+85+240',
        'total' => null,
        'notes' => '895',
    ],
    [
        'transaction_number' => 279,
        'date' => '2026-03-02',
        'customer_name' => 'اماني زميله هبه',
        'product' => 'بجامه حريمي + ترنج ولادي + دفاية + بنطلون جينز',
        'quantity' => '1',
        'unit_price' => '500',
        'total' => 500.0,
        'notes' => '300+120+350=770',
    ],
    [
        'transaction_number' => 280,
        'date' => '2026-03-02',
        'customer_name' => 'رقفه زميله هبه',
        'product' => '4 دفايات + ترنج حريمي + بوكسر',
        'quantity' => '6',
        'unit_price' => '440+500+85',
        'total' => null,
        'notes' => '1025',
    ],
    [
        'transaction_number' => 281,
        'date' => '2026-03-02',
        'customer_name' => 'دعاء زميله هبه',
        'product' => 'بيجامه بناتي',
        'quantity' => '1',
        'unit_price' => '350',
        'total' => null,
        'notes' => '350',
    ],
    [
        'transaction_number' => 282,
        'date' => '2026-03-02',
        'customer_name' => 'سلوي زميله هبه',
        'product' => 'ترنج رجالي',
        'quantity' => '1',
        'unit_price' => '330',
        'total' => null,
        'notes' => '330',
    ],
    [
        'transaction_number' => 283,
        'date' => '2026-03-03',
        'customer_name' => 'عميل محل',
        'product' => '2 هودي + 3 شروال alo + طقمين داخلي',
        'quantity' => '7',
        'unit_price' => '350+350+350+400+400+200',
        'total' => 2050.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 284,
        'date' => '2026-03-03',
        'customer_name' => 'احمد زناتي',
        'product' => '2 دفايه عرايس + دفايه حريمي',
        'quantity' => '3',
        'unit_price' => '100+100+120',
        'total' => 320.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 285,
        'date' => '2026-03-03',
        'customer_name' => 'محمد السيد',
        'product' => '2 بجامه زراير + ترنج + ترنج',
        'quantity' => '4',
        'unit_price' => '390+390+200+220',
        'total' => 1200.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 286,
        'date' => '2026-03-03',
        'customer_name' => 'بضاعه دلعين',
        'product' => 'داخلي',
        'quantity' => null,
        'unit_price' => null,
        'total' => -4100.0,
        'notes' => null,
    ],
    [
        'transaction_number' => 287,
        'date' => null,
        'customer_name' => 'مني حسن زميله هبه',
        'product' => 'بنطلون جينز',
        'quantity' => '1',
        'unit_price' => '350',
        'total' => null,
        'notes' => '350',
    ],
];
